version: "3.7"

services:
  pgadmin:
    image: dpage/pgadmin4
    environment: 
        - PGADMIN_DEFAULT_EMAIL=ain@ain.com
        - PGADMIN_DEFAULT_PASSWORD=123
    ports: 
        - "5050:80"
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    # ports:
    #   - 5432:5432
    environment:
      # - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    network_mode: host

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  # app:
  #   build: .
  #   container_name: rentx
  #   # ports:
  #   #   - 3333:3333
  #   volumes:
  #     - .:/user/app
  #   network_mode: host

volumes:
  pgdata:
    driver: local